-- Crescer+ / Supabase — provedores de e-mail e auditoria administrativa

create table if not exists public.email_providers (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('native', 'resend', 'mailtrap')),
  name text not null,
  enabled boolean not null default false,
  from_email text not null default '',
  from_name text not null default 'Crescer+',
  reply_to text not null default '',
  secret_env_name text not null default '',
  config_json jsonb not null default '{}'::jsonb,
  last_tested_at timestamptz null,
  last_test_status text null check (last_test_status in ('ok', 'failed', 'manual')),
  last_test_message text null,
  created_by uuid null references public.users(id) on delete set null,
  updated_by uuid null references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_email_providers_provider on public.email_providers(provider);
create index if not exists idx_email_providers_enabled on public.email_providers(enabled);

create table if not exists public.email_deliveries (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid null references public.email_providers(id) on delete set null,
  event_type text not null check (event_type in ('signup','invite','recovery','magiclink','email_change','notification','test')),
  recipient text not null,
  subject text not null default '',
  status text not null check (status in ('sent','failed','manual')),
  provider_message_id text null,
  error_message text null,
  created_by uuid null references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_email_deliveries_created_at on public.email_deliveries(created_at desc);
create index if not exists idx_email_deliveries_status on public.email_deliveries(status, created_at desc);
create index if not exists idx_email_deliveries_event_type on public.email_deliveries(event_type, created_at desc);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('SELECT','INSERT','UPDATE','DELETE','LOGIN','LOGOUT','SEND_EMAIL','SYSTEM')),
  resource text not null,
  resource_id text null,
  actor_user_id uuid null references public.users(id) on delete set null,
  actor_email text null,
  actor_name text null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_action on public.audit_logs(action, created_at desc);
create index if not exists idx_audit_logs_resource on public.audit_logs(resource, created_at desc);
create index if not exists idx_audit_logs_actor_email on public.audit_logs(actor_email, created_at desc);

alter table public.email_providers enable row level security;
alter table public.email_deliveries enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "email_providers_super_admin" on public.email_providers;
drop policy if exists "email_deliveries_super_admin" on public.email_deliveries;
drop policy if exists "audit_logs_super_admin" on public.audit_logs;

create policy "email_providers_super_admin" on public.email_providers
for all to authenticated
using ((select private.is_super_admin()))
with check ((select private.is_super_admin()));

create policy "email_deliveries_super_admin" on public.email_deliveries
for select to authenticated
using ((select private.is_super_admin()));

create policy "audit_logs_super_admin" on public.audit_logs
for select to authenticated
using ((select private.is_super_admin()));

insert into public.email_providers (provider, name, enabled, from_name, secret_env_name, config_json)
values
  ('native', 'Supabase Auth nativo', true, 'Crescer+', '', '{"description":"Usa o SMTP configurado no Supabase Auth. Para produção, configure SMTP customizado no dashboard do Supabase."}'::jsonb),
  ('resend', 'Resend', false, 'Crescer+', 'RESEND_API_KEY', '{"api_url":"https://api.resend.com/emails","docs_url":"https://resend.com/docs/api-reference/emails/send-email"}'::jsonb),
  ('mailtrap', 'Mailtrap', false, 'Crescer+', 'MAILTRAP_API_TOKEN', '{"api_url":"https://send.api.mailtrap.io/api/send","docs_url":"https://docs.mailtrap.io/developers/email-sending/transactional"}'::jsonb)
on conflict (provider) do nothing;

insert into public.app_settings (key, value_json)
values
  ('email.default_provider', to_jsonb('native'::text)),
  ('email.fallback_provider', to_jsonb(''::text)),
  ('email.auth_hook_enabled', to_jsonb(false)),
  ('email.from_email', to_jsonb(''::text)),
  ('email.from_name', to_jsonb('Crescer+'::text)),
  ('email.reply_to', to_jsonb(''::text)),
  ('email.test_recipient', to_jsonb(''::text))
on conflict (key) do nothing;

create or replace function private.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_email text;
  v_actor_name text;
  v_row jsonb;
  v_resource_id text;
begin
  select email, name into v_actor_email, v_actor_name from public.users where id = v_actor;
  if tg_op = 'DELETE' then
    v_row := to_jsonb(old);
  else
    v_row := to_jsonb(new);
  end if;
  v_row := v_row - 'token' - 'password' - 'senha_hash';
  v_resource_id := coalesce(v_row ->> 'id', v_row ->> 'key', v_row ->> 'prompt_key');

  insert into public.audit_logs (action, resource, resource_id, actor_user_id, actor_email, actor_name, details)
  values (
    tg_op,
    tg_table_name,
    v_resource_id,
    v_actor,
    coalesce(v_actor_email, 'sistema'),
    coalesce(v_actor_name, 'Sistema'),
    jsonb_build_object('row', v_row)
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

revoke all on function private.audit_row_change() from public, anon, authenticated;

drop trigger if exists audit_users_change on public.users;
create trigger audit_users_change after insert or update or delete on public.users for each row execute function private.audit_row_change();
drop trigger if exists audit_children_change on public.children;
create trigger audit_children_change after insert or update or delete on public.children for each row execute function private.audit_row_change();
drop trigger if exists audit_activities_change on public.activities;
create trigger audit_activities_change after insert or update or delete on public.activities for each row execute function private.audit_row_change();
drop trigger if exists audit_age_stages_change on public.age_stages;
create trigger audit_age_stages_change after insert or update or delete on public.age_stages for each row execute function private.audit_row_change();
drop trigger if exists audit_categories_change on public.categories;
create trigger audit_categories_change after insert or update or delete on public.categories for each row execute function private.audit_row_change();
drop trigger if exists audit_invites_change on public.invites;
create trigger audit_invites_change after insert or update or delete on public.invites for each row execute function private.audit_row_change();
drop trigger if exists audit_app_settings_change on public.app_settings;
create trigger audit_app_settings_change after insert or update or delete on public.app_settings for each row execute function private.audit_row_change();
drop trigger if exists audit_email_providers_change on public.email_providers;
create trigger audit_email_providers_change after insert or update or delete on public.email_providers for each row execute function private.audit_row_change();
drop trigger if exists audit_email_deliveries_change on public.email_deliveries;
create trigger audit_email_deliveries_change after insert or update or delete on public.email_deliveries for each row execute function private.audit_row_change();

create or replace function public.record_audit_event(
  p_action text,
  p_resource text,
  p_resource_id text default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_email text;
  v_actor_name text;
  v_id bigint;
begin
  if v_actor is null then raise exception 'Sessão ausente'; end if;
  if p_action not in ('SELECT','LOGIN','LOGOUT') then raise exception 'Ação não permitida'; end if;
  select email, name into v_actor_email, v_actor_name from public.users where id = v_actor;
  insert into public.audit_logs (action, resource, resource_id, actor_user_id, actor_email, actor_name, details)
  values (p_action, left(coalesce(p_resource, 'app'), 120), left(p_resource_id, 120), v_actor, v_actor_email, v_actor_name, coalesce(p_details, '{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.record_audit_event(text, text, text, jsonb) from public, anon;
grant execute on function public.record_audit_event(text, text, text, jsonb) to authenticated;
